format = '''
$os â¯ $directory $git_branch$python$java$nodejs$fill$cmd_duration$time
$character
'''

[fill]
symbol = ' '

[time]
disabled = false
style = "white regular"
format = "[$time]($style) "
time_format = '%R'

[cmd_duration]
format = "took [$duration](red bold) / "
min_time = 100

[os]
format = "[$symbol]($style)"
style = "fg:#ab8cf5"
disabled = false

[os.symbols]
Macos = "ïŒ‚"

[git_branch]
style = 'red bold'
format = "[$symbol$branch(:$remote_branch)]($style) "
truncation_length = 4
truncation_symbol = ''

[username]
style_user = "fg:#ab8cf5 bold"
style_root = "red bold"
format = '[chon]($style)'
show_always = true

[directory]
read_only = " ï ½"
style = 'cyan bold italic'
format = '[$path]($style)'
truncate_to_repo = false

# [package]
# symbol = "ï£–"
# format = 'via [$symbol $version](208 bold)'

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[âœ—](bold red)'

[python]
symbol = "î˜† "
format = 'via [${symbol}${version}]($style)'
style = "bold yellow"
python_binary = 'python3'

[java]
symbol = "î‰– "
format = 'via [${symbol}${version}]($style)'
style = "bold red"

[nodejs]
symbol = "îœ˜ "
format = 'via [${symbol}${version}]($style)'
style = "bold green"

[c]
symbol = "î˜ "
format = 'via [${symbol}${version}]($style)'
style = "bold cyan"

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "

[golang]
symbol = "î˜§ "

[guix_shell]
symbol = "ïŒ¥ "

[haskell]
symbol = "î· "

[haxe]
symbol = "âŒ˜ "

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "

[meson]
symbol = "ï¨¶ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "